version: '3.0'
services:
  jobengine: 
    container_name: jobengine
    build:
      context: .
      dockerfile: Dockerfile
    image: michaelwittgreffe:jobengine
    environment:
      SECRET: hello_world
      GIN_MODE: release
      CONFIG_PATH: /jobengine/files/config.yml
      DB_PATH: /jobengine/files/queues.queuedb
    volumes:
      - "./examples:/jobengine/files"
    ports: 
      - 6001:6010