version: 1
port: 6010
job_keep_minutes: 30
job_timeout_minutes: 30
queues:
  test_queue_1:
    read:
    - service1
    - service2
    write:
    - service3
  test_queue_2:
    read:
    - service3
    write:
    - service1
    - service2
  test_queue_3:
    read:
      - service4
    write:
      - service4
  test_queue_4:
    read:
      - service5
    write:
      - service6